import*as i from"@angular/core";import{RendererFactory2 as l,NgZone as A,ANIMATION_MODULE_TYPE as c}from"@angular/core";import{ANIMATION_MODULE_TYPE as x}from"@angular/core";import{\u0275DomRendererFactory2 as v,BrowserModule as d}from"@angular/platform-browser";import*as o from"@angular/animations/browser";import{\u0275AnimationEngine as r,\u0275WebAnimationsStyleNormalizer as N,\u0275AnimationRendererFactory as y,\u0275AnimationStyleNormalizer as D,AnimationDriver as u,\u0275WebAnimationsDriver as M,NoopAnimationDriver as I}from"@angular/animations/browser";import{DOCUMENT as R}from"@angular/common";var O=(()=>{class e extends r{constructor(t,n,f,j){super(t,n,f)}ngOnDestroy(){this.flush()}static{this.\u0275fac=function(n){return new(n||e)(i.\u0275\u0275inject(R),i.\u0275\u0275inject(o.AnimationDriver),i.\u0275\u0275inject(o.\u0275AnimationStyleNormalizer),i.\u0275\u0275inject(i.ApplicationRef))}}static{this.\u0275prov=i.\u0275\u0275defineInjectable({token:e,factory:e.\u0275fac})}}return e})();function g(){return new N}function E(e,p,t){return new y(e,p,t)}var m=[{provide:D,useFactory:g},{provide:r,useClass:O},{provide:l,useFactory:E,deps:[v,r,A]}],a=[{provide:u,useFactory:()=>new M},{provide:c,useValue:"BrowserAnimations"},...m],s=[{provide:u,useClass:I},{provide:c,useValue:"NoopAnimations"},...m],_=(()=>{class e{static withConfig(t){return{ngModule:e,providers:t.disableAnimations?s:a}}static{this.\u0275fac=function(n){return new(n||e)}}static{this.\u0275mod=i.\u0275\u0275defineNgModule({type:e})}static{this.\u0275inj=i.\u0275\u0275defineInjector({providers:a,imports:[d]})}}return e})();function V(){return[...a]}var z=(()=>{class e{static{this.\u0275fac=function(n){return new(n||e)}}static{this.\u0275mod=i.\u0275\u0275defineNgModule({type:e})}static{this.\u0275inj=i.\u0275\u0275defineInjector({providers:s,imports:[d]})}}return e})();function B(){return[...s]}export{x as ANIMATION_MODULE_TYPE,_ as BrowserAnimationsModule,z as NoopAnimationsModule,V as provideAnimations,B as provideNoopAnimations,O as \u0275InjectableAnimationEngine};
/*! Bundled license information:

@angular/platform-browser/fesm2022/animations.mjs:
  (**
   * @license Angular v17.0.7
   * (c) 2010-2022 Google LLC. https://angular.io/
   * License: MIT
   *)
*/
