import*as i from"@angular/core";import{inject as l,\u0275ChangeDetectionScheduler as A,RendererFactory2 as v,NgZone as N,ANIMATION_MODULE_TYPE as c}from"@angular/core";import{ANIMATION_MODULE_TYPE as U}from"@angular/core";import{\u0275DomRendererFactory2 as y,BrowserModule as d}from"@angular/platform-browser";import*as o from"@angular/animations/browser";import{\u0275AnimationEngine as r,\u0275WebAnimationsStyleNormalizer as D,\u0275AnimationRendererFactory as M,\u0275AnimationStyleNormalizer as I,AnimationDriver as u,\u0275WebAnimationsDriver as g,NoopAnimationDriver as O}from"@angular/animations/browser";import{DOCUMENT as R}from"@angular/common";var h=(()=>{class e extends r{constructor(t,n,f){super(t,n,f,l(A,{optional:!0}))}ngOnDestroy(){this.flush()}static{this.\u0275fac=function(n){return new(n||e)(i.\u0275\u0275inject(R),i.\u0275\u0275inject(o.AnimationDriver),i.\u0275\u0275inject(o.\u0275AnimationStyleNormalizer))}}static{this.\u0275prov=i.\u0275\u0275defineInjectable({token:e,factory:e.\u0275fac})}}return e})();function E(){return new D}function S(e,p,t){return new M(e,p,t)}var m=[{provide:I,useFactory:E},{provide:r,useClass:h},{provide:v,useFactory:S,deps:[y,r,N]}],a=[{provide:u,useFactory:()=>new g},{provide:c,useValue:"BrowserAnimations"},...m],s=[{provide:u,useClass:O},{provide:c,useValue:"NoopAnimations"},...m],C=(()=>{class e{static withConfig(t){return{ngModule:e,providers:t.disableAnimations?s:a}}static{this.\u0275fac=function(n){return new(n||e)}}static{this.\u0275mod=i.\u0275\u0275defineNgModule({type:e})}static{this.\u0275inj=i.\u0275\u0275defineInjector({providers:a,imports:[d]})}}return e})();function V(){return[...a]}var z=(()=>{class e{static{this.\u0275fac=function(n){return new(n||e)}}static{this.\u0275mod=i.\u0275\u0275defineNgModule({type:e})}static{this.\u0275inj=i.\u0275\u0275defineInjector({providers:s,imports:[d]})}}return e})();function B(){return[...s]}export{U as ANIMATION_MODULE_TYPE,C as BrowserAnimationsModule,z as NoopAnimationsModule,V as provideAnimations,B as provideNoopAnimations,h as \u0275InjectableAnimationEngine};
/*! Bundled license information:

@angular/platform-browser/fesm2022/animations.mjs:
  (**
   * @license Angular v17.1.3
   * (c) 2010-2022 Google LLC. https://angular.io/
   * License: MIT
   *)
*/
